name: Atlas CI

on:
  pull_request:
    paths:
      - 'migrations/*' # Run only if changes occur in the migrations directory

permissions:
  contents: read
  pull-requests: write

jobs:
  atlas-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 1: Setup Atlas
      - uses: ariga/setup-atlas@v0
        with:
          cloud-token: ${{ secrets.ATLAS_TOKEN }}

      # Step 2: Lint the migrations
      - uses: ariga/atlas-action/migrate/lint@v1
        with:
          dir-name: 'neon-locks'
          env: "neon"
        env:
          GITHUB_TOKEN: ${{ github.token }}

      # Step 3: Create a new branch using the Neon official action
      - name: Create Neon Branch
        id: create-branch
        uses: neondatabase/create-branch-action@v5
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          api_key: ${{ secrets.NEON_API_KEY }}
          branch_name: pr-${{ github.event.number }}
          username: neondb_owner

      # Step 4: Apply migrations and save the exit code
      - name: Apply Migrations
        id: apply-migrations
        run: |
          set +e  # Don't exit immediately on error
          atlas migrate apply --env neon --url="${{ steps.create-branch.outputs.db_url }}&search_path=public" --dir "file://migrations"
          MIGRATION_EXIT_CODE=$?
          echo "status=$MIGRATION_EXIT_CODE" >> $GITHUB_OUTPUT
          set -e  # Restore normal bash behavior
        
      # Step 5: Always clean up the Neon branch
      - name: Clean up Neon Branch
        if: always()
        uses: neondatabase/delete-branch-action@v3
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          api_key: ${{ secrets.NEON_API_KEY }}
          branch: pr-${{ github.event.number }}
          
      # Step 6: Fail workflow if migrations failed
      - name: Check Migration Status
        if: ${{ always() }}  # Always run this step
        run: |
          if [[ "${{ steps.apply-migrations.outputs.status }}" != "0" ]]; then
            echo "Migration failed with status code ${{ steps.apply-migrations.outputs.status }}"
            echo "::error::Atlas migration failed to apply. This build is marked as failed to prevent merging migrations with errors."
            exit 1
          else
            echo "Migrations applied successfully"
          fi
